### ISSUE TITLE
Prerendering failed because of error: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by JSGund** [kartik-budhiraja/react-wavy-audio#2]
I have installed the library: **npm install react-wavy-audio**, Once I ran the application and getting the below exception in the browser.

Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: Prerendering failed because of error: ReferenceError: window is not defined
    at eval (webpack-internal:///./node_modules/react-wavy-audio/dist/index.js:40:4)
    at createCommonjsModule (webpack-internal:///./node_modules/react-wavy-audio/dist/index.js:29:35)
    at eval (webpack-internal:///./node_modules/react-wavy-audio/dist/index.js:32:18)
    at Object../node_modules/react-wavy-audio/dist/index.js

@kartik-budhiraja can you please help me out to resolve this exception?

**Comment by kartik-budhiraja** [comment]
@JSGund Are you pre-rendering the view on server? We use `waveform.js` under the hood, which needs window to be defined. You will need to put some logic around any code that tries to reference this library so that it doesn't run during server-side prerendering. For example, use a check like `if (typeof window !== 'undefined') { ... run client-side code ... }`.

**Comment by JSGund** [comment]
yes, it's pre-rendering the view on the server? any solution for it.

**Comment by kartik-budhiraja** [comment]
I don't think you can pre-render it considering the waveform.js needs window to be defined.
